"""Tests for the competing risky-choice models and the comparison harness (roadmap 2.2; exp058)."""

import numpy as np

from behavioral_md import choice_models as cm
from behavioral_md.survival import skewed_outcomes


def _pair(skew, mean=0.6, std=0.2):
    return skewed_outcomes(mean, std, skew), skewed_outcomes(mean, std, -skew)


def test_moments_match_construction():
    """moments() recovers the constructed mean, variance, and skew sign."""
    g = skewed_outcomes(0.6, 0.2, 0.8)
    m, var, skew = cm.moments(g)
    assert abs(m - 0.6) < 1e-6
    assert abs(var - 0.04) < 1e-4
    assert skew > 0.3                                  # right-skewed


def test_mean_variance_is_skew_blind():
    """At matched mean+variance the mean-variance model predicts exact indifference for any skew."""
    for s in (0.3, 0.7, 1.2):
        A, B = _pair(s)
        assert abs(cm.predict_choice(cm.mv_value, A, B, b=3.0, beta=10.0) - 0.5) < 1e-9


def test_eu_and_pt_are_skew_sensitive():
    """A curved-utility EU (c>0, prudent) and prospect theory both prefer the positively skewed
    gamble at matched mean+variance -- they are NOT skew-blind."""
    A, B = _pair(0.9)
    assert cm.predict_choice(cm.eu_value, A, B, a=0.3, c=4.0, beta=8.0) > 0.55
    assert cm.predict_choice(cm.pt_value, A, B, beta=6.0) > 0.55


def test_survival_skew_preference_reverses_at_R():
    """The survival-DP's distinguishing prediction: the skew preference reverses across the
    requirement R -- prefers the negatively skewed gamble below R, the positively skewed above."""
    day, night, metab = 14, 16, 0.03
    R = night * metab
    A, B = skewed_outcomes(0.05, 0.03, 0.9), skewed_outcomes(0.05, 0.03, -0.9)
    below = cm.survival_advantage(A, B, 0.6 * R, day, night, metab, n_egrid=801)
    above = cm.survival_advantage(A, B, 1.0 * R, day, night, metab, n_egrid=801)
    assert below < 0 < above                           # -skew preferred below R, +skew above


def test_skew_blind_model_loses_on_skew_data():
    """Model recovery: data generated by a skew-sensitive model (EU with prudence) is fit far worse
    by the skew-blind mean-variance model than by a skew-sensitive one (AIC)."""
    rng = np.random.default_rng(0)
    trials = []
    for s in np.linspace(-1.1, 1.1, 10):
        for dv in (0.0, 0.12, -0.12):
            A = skewed_outcomes(0.6 + dv, 0.2, float(s))
            B = skewed_outcomes(0.6, 0.2, -float(s))
            p = cm.predict_choice(cm.eu_value, A, B, a=0.3, c=4.0, beta=9.0)
            trials.append({"A": A, "B": B, "n": 40, "k": int(rng.binomial(40, p))})
    fits = {f["name"]: f for f in cm.compare_models(trials, names=("mv", "eu", "pt"))}
    assert fits["eu"]["aic"] < fits["mv"]["aic"] - 10   # skew-sensitive model clearly wins
    assert fits["mv"]["delta_aic"] > 10


def test_fit_recovers_and_aic_counts_params():
    """fit_model returns a parameter dict including beta and an AIC that counts all free params."""
    A, B = _pair(0.8)
    trials = [{"A": A, "B": B, "n": 50, "k": 40}, {"A": B, "B": A, "n": 50, "k": 10}]
    fit = cm.fit_model("eu", trials)
    assert set(fit["params"]) == {"a", "c", "beta"}
    assert np.isclose(fit["aic"], 2 * fit["n_params"] + 2 * fit["negloglik"])
